import type { Metadata } from "next";
import { Inter, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
import StoreProvider from "@/components/Provider/StoreProvider";
import { Suspense } from "react";
import Loading from "./loading";
import { Toaster } from "@/components/ui/toaster"


const Header = dynamic(() => import('@/components/Header/Header'), { ssr: false });
const Footer = dynamic(() => import("@/components/Footer/Footer"), { ssr: false });

// const inter = Inter({ subsets: ["latin"] });
const roboto_condensed = Roboto_Condensed({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "WinKhin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto_condensed.className}>
        <StoreProvider
          cart={[]}
        >
          <Toaster />
          <Header />
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
